### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by lskatz**
Hey @azumakuniyuki , 
I am suggesting this pull request which changes the structure of the repo.  There are several advantages:

* Uses standard `Makefile.PL` syntax which is a standardized workflow
    * `perl Makefile.PL`
    * make
    * make test
* Keeps track of dependencies and feeds into some workflows like `cpanm --installdeps .`
* Streamlines with continuous integration
    * Makes GitHub run all the scripts automatically on the new Actions tab above
    *  For example: https://github.com/lskatz/make-perl-code-faster/runs/1226493702?check_suite_focus=true

There are some new file changes:
* Makefile.PL instead of Makefile
* .github folder with workflow file
* t directory with perl tests.  Perl tests have a .t extension.

### CODE REVIEW

**Comment by lskatz** [comment]
And the biggest advantage of all: the GitHub server will run everything for you and on different platforms and perl versions!

**Comment by azumakuniyuki** [comment]
@lskatz Thanks for the suggestion, It looks a great work! I will merge this P/R after the following changes:

- Keep the current structure with tag `v1.0.0` because some articles in the paper refer to URL `https://github.com/azumakuniyuki/make-perl-code-faster/<filename>.pl`
- `git branch -b without-github-actions` at the master branch

**Comment by lskatz** [comment]
Thank you for being open to this idea!

Is it possible to change the links in `README.md` instead of returning the files to the main directory?  The `t/` directory is the more standard convention.

I can merge with `without-github-actions` if that is what you are suggesting, sure.

**Comment by azumakuniyuki** [comment]
We're sorry for the late response. This P/R has been merged into `master` branch now.

**Comment by azumakuniyuki** [comment]
We've updated the followings:
- README.md
- `Makefile.nonstandard` => `Developers.mk`

**Pull request merged**
