### PR TITLE
local database comparison

### PR DESCRIPTION
**Pull request by lskatz**
Three major categories tested: insert update select

### CODE REVIEW

**Comment by azumakuniyuki** [comment]
Thanks for the Pull-Request :-) `local-database.pl` is a good benchmark code but we can not accept this Pull-Request because it includes a commit for `check-first-character.pl`.

Would you create a new Pull-Request including only commits for `local-database.pl` ?

**Comment by lskatz** [comment]
Hopefully these new changes address your concerns

**Comment by azumakuniyuki** [comment]
Thanks for the Pull-Request, but your Pull-Request is too large. Please create a Pull-Request including changes for only one file.

Best regards.

**Comment by lskatz** [comment]
I have reduced the pull request to just `local-database.pl`

**Pull request merged**
